global:
  edition: ce
  hosts:
    domain: localhost
    gitlab:
      name: localhost
      port: 8082
  ingress:
    enabled: false

certmanager:
  enabled: false

certmanager-issuer:
  email: admin@example.com

nginx-ingress:
  enabled: false

postgresql:
  enabled: true

redis:
  enabled: true

gitaly:
  enabled: true

minio:
  enabled: false

registry:
  enabled: false

gitlab:
  webservice:
    service:
      type: LoadBalancer
      port: 8082
  sidekiq:
    enabled: true
